/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Invoice;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceRecord extends UpdatableRecordImpl<InvoiceRecord> implements Record3<Integer, Date, String> {

    private static final long serialVersionUID = 1542036661;

    /**
     * Setter for <code>public.Invoice.id</code>.
     */
    public InvoiceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.Invoice.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Invoice.organization_date</code>.
     */
    public InvoiceRecord setOrganizationDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.Invoice.organization_date</code>.
     */
    public Date getOrganizationDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.Invoice.organization_name</code>.
     */
    public InvoiceRecord setOrganizationName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.Invoice.organization_name</code>.
     */
    public String getOrganizationName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Date, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Date, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Invoice.INVOICE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Invoice.INVOICE.ORGANIZATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Invoice.INVOICE.ORGANIZATION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getOrganizationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrganizationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getOrganizationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganizationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceRecord value2(Date value) {
        setOrganizationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceRecord value3(String value) {
        setOrganizationName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceRecord values(Integer value1, Date value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceRecord
     */
    public InvoiceRecord() {
        super(Invoice.INVOICE);
    }

    /**
     * Create a detached, initialised InvoiceRecord
     */
    public InvoiceRecord(Integer id, Date organizationDate, String organizationName) {
        super(Invoice.INVOICE);

        set(0, id);
        set(1, organizationDate);
        set(2, organizationName);
    }
}
