/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Invoice;
import db.tables.Invoicepositions;
import db.tables.Nomenclature;
import db.tables.Organization;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.Invoice</code>.
     */
    public static final Invoice INVOICE = db.tables.Invoice.INVOICE;

    /**
     * The table <code>public.InvoicePositions</code>.
     */
    public static final Invoicepositions INVOICEPOSITIONS = db.tables.Invoicepositions.INVOICEPOSITIONS;

    /**
     * The table <code>public.Nomenclature</code>.
     */
    public static final Nomenclature NOMENCLATURE = db.tables.Nomenclature.NOMENCLATURE;

    /**
     * The table <code>public.Organization</code>.
     */
    public static final Organization ORGANIZATION = db.tables.Organization.ORGANIZATION;
}
